/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e88b6eec-30df-49c6-9570-0f00e9e30ae2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_hl0mWEfbC",
    "aws_user_pools_web_client_id": "4ashdv3vl3085ns6s8pu83uopm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rmrmrhyczbclnftvz4tupavx5q.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rvzcief37bbrrbk2eplghbez3q"
};


export default awsmobile;
